apiVersion: v1
kind: Deployment
metadata: 
   name: mydeployments

spec:
   replicas: 3
   selectors:
     matchLables:
       type: front-end
   template:
       metadata:
          name: my-app
          labels:
            type: front-end

       spec:
        - containers:
           - name: webserver
             image: nginx2.1
             imagepullpolicy: always
             ports:
              - containerPort: 80  
